name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./Front-e2e
        run: npm install



      - name: Start frontend server
        working-directory: ./Front-e2e
        run: npm run dev &
        env:
          CI: true

      - name: Wait for frontend to be ready
        uses: jakejarvis/wait-action@master
        with:
            url: http://localhost:52594
            timeout: 60
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:52594'
          wait-on-timeout: 60
          working-directory: ./Front-e2e
        env:
          CI: true
