name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./Front-e2e
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --config baseUrl=https://test-adl.leonardojose.dev
        working-directory: ./Front-e2e
        env:
          CI: true
